### ISSUE TITLE
Cannot run npm install

### ISSUE THREAD

**Issue by PaulMcGuinness** [sgratzl/chartjs-chart-pcp#2]
When running **npm install** I get the following error

D:\Temp\node_modules\chartjs-chart-pcp>npm install

> chartjs-chart-pcp@1.0.0 prepare D:\Temp\node_modules\chartjs-chart-pcp
> npm run build:dev

> chartjs-chart-pcp@1.0.0 build:dev D:\Temp\node_modules\chartjs-chart-pcp
> rollup -c -i src/index.js

```
[!] Error: Could not resolve entry module (rollup.config.js).
Error: Could not resolve entry module (rollup.config.js).
    at error (D:\Temp\node_modules\chartjs-chart-pcp\node_modules\rollup\dist\shared\rollup.js:161:30)
    at ModuleLoader.loadEntryModule (D:\Temp\node_modules\chartjs-chart-pcp\node_modules\rollup\dist\shared\rollup.js:17598:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chartjs-chart-pcp@1.0.0 build:dev: `rollup -c -i src/index.js`
npm ERR! Exit status 1
```

**Comment by sgratzl** [comment]
can you describe how to reproduce it step by step, please

**Comment by PaulMcGuinness** [comment]
From an elevated DOS command prompt in Windows 10:-

```
md a
cd a
npm install --save chart.js chartjs-chart-pcp
```
(wait for it to download)
```
cd node_modules
cd chartjs-chart-pcp
npm install
```
starts throwing up a *lot* of deprecated errors....then this:-

```
npm WARN deprecated rollup-plugin-babel@4.4.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-babel.
npm WARN deprecated rollup-watch@4.3.1: rollup-watch functionality is now included in Rollup itself
npm WARN deprecated rollup-plugin-commonjs@10.1.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.
npm WARN deprecated rollup-plugin-node-resolve@5.2.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
npm WARN deprecated chokidar@1.7.0: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

> chartjs-chart-pcp@1.0.0 prepare D:\a\node_modules\chartjs-chart-pcp
> npm run build:dev


> chartjs-chart-pcp@1.0.0 build:dev D:\a\node_modules\chartjs-chart-pcp
> rollup -c -i src/index.js

[!] Error: Could not resolve entry module (rollup.config.js).
Error: Could not resolve entry module (rollup.config.js).
    at error (D:\a\node_modules\chartjs-chart-pcp\node_modules\rollup\dist\shared\rollup.js:161:30)
    at ModuleLoader.loadEntryModule (D:\a\node_modules\chartjs-chart-pcp\node_modules\rollup\dist\shared\rollup.js:17598:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chartjs-chart-pcp@1.0.0 build:dev: `rollup -c -i src/index.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chartjs-chart-pcp@1.0.0 build:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Paul McGuinness\AppData\Roaming\npm-cache\_logs\2020-05-26T13_40_29_722Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! chartjs-chart-pcp@1.0.0 prepare: `npm run build:dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chartjs-chart-pcp@1.0.0 prepare script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Paul McGuinness\AppData\Roaming\npm-cache\_logs\2020-05-26T13_40_29_830Z-debug.log

D:\a\node_modules\chartjs-chart-pcp>
```

**Comment by sgratzl** [comment]
```
cd node_modules
cd chartjs-chart-pcp
npm install
```

why this step?

**Comment by PaulMcGuinness** [comment]
[2020-05-26T13_40_29_722Z-debug.log](https://github.com/sgratzl/chartjs-chart-pcp/files/4682614/2020-05-26T13_40_29_722Z-debug.log)

Here is the npm log file

**Comment by PaulMcGuinness** [comment]
because that's what your instructions say? 

**Building**
npm install
npm run build


I'm just after a normal .js file to include in a web-page front end, not a back-end Node module. 

Do please tell me if I'm being a muppet :-)

**Comment by PaulMcGuinness** [comment]
( the examples shows ../build/Chart.PCP.js   but I can't find the 'build' version, so I assumed that's what I had to do?)

**Comment by sgratzl** [comment]
those instruction are in case you want to build the library in case you check it out the repository and develop it yourself. 

In your case you can just download the file from: 

https://github.com/sgratzl/chartjs-chart-pcp/releases -> assets -> Chart.PCP.js

or link to it via a CDN like unpkg in your website

https://unpkg.com/chartjs-chart-pcp

or take the installed built files in your case in: `node_modules/chartjs-chart-pcp/build/Chart.PCP.js`

**Comment by PaulMcGuinness** [comment]
Many thanks - I'm glad I was just being a muppet :-)
